### PR TITLE
Feature/30 enums

### LINKED ISSUE #30: IntEnums
For connector relation types, because I'm bored of writing it in dependent projects.

Should probably also fill out the catpy.image.TileSourceType one, for completeness.

### PR DESCRIPTION
**Pull request by clbarnes**
resolves #30

### CODE REVIEW

**Comment by aschampion** [comment]
I think we want to not assume relation IDs are always the same and can be project-defined. Endpoint docs are legacy and should be updated. Relation IDs should be fetched and cached once per-project.

**Comment by clbarnes** [comment]
Rebased on master

**Comment by clbarnes** [comment]
> I think we want to not assume relation IDs are always the same and can be project-defined. Endpoint docs are legacy and should be updated. Relation IDs should be fetched and cached once per-project.

Makes sense. In that case, I guess it'd be better to define the enum using the string representations here https://github.com/catmaid/CATMAID/blob/master/django/applications/catmaid/control/connector.py#L35 , and then make a method/function which returns a list of `(relation_id, relation_name)` tuples, so that users can do the mapping both ways.

The enum could be scrapped entirely if we're treating the relations as dynamic, but that doesn't quite feel right either.

**Comment by clbarnes** [comment]
Rebased on master after #28

**Comment by clbarnes** [comment]
@aschampion done. Adds some complexity but I think it's the best way to do it while still keeping the nice bits of enums.

**Pull request merged**
